// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHF5tbHWcaHX_nJlSWcu8QTTeCB38Kr2o',
    appId: '1:895799744707:web:f146cfe44bfdd33368ea76',
    messagingSenderId: '895799744707',
    projectId: 'attendify-f8194',
    authDomain: 'attendify-f8194.firebaseapp.com',
    storageBucket: 'attendify-f8194.firebasestorage.app',
    measurementId: 'G-HKJHM06ZV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA0QX8vSpiwshXYwSCc01Tyq9iOXsY3uU',
    appId: '1:895799744707:android:fdf22368773a02d968ea76',
    messagingSenderId: '895799744707',
    projectId: 'attendify-f8194',
    storageBucket: 'attendify-f8194.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYMnI7FvOFXGmLax-TSH2hV-G17muxC24',
    appId: '1:895799744707:ios:219077bf75f3bc2c68ea76',
    messagingSenderId: '895799744707',
    projectId: 'attendify-f8194',
    storageBucket: 'attendify-f8194.firebasestorage.app',
    iosBundleId: 'com.example.tubesAttendify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYMnI7FvOFXGmLax-TSH2hV-G17muxC24',
    appId: '1:895799744707:ios:219077bf75f3bc2c68ea76',
    messagingSenderId: '895799744707',
    projectId: 'attendify-f8194',
    storageBucket: 'attendify-f8194.firebasestorage.app',
    iosBundleId: 'com.example.tubesAttendify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHF5tbHWcaHX_nJlSWcu8QTTeCB38Kr2o',
    appId: '1:895799744707:web:9816efae89df740f68ea76',
    messagingSenderId: '895799744707',
    projectId: 'attendify-f8194',
    authDomain: 'attendify-f8194.firebaseapp.com',
    storageBucket: 'attendify-f8194.firebasestorage.app',
    measurementId: 'G-GBP7YFRTJ6',
  );

}